export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_SINGIN = 'FETCH_SINGIN';
export const FETCH_SINGIN_SUCCESS = 'FETCH_SINGIN_SUCCESS';
export const FETCH_SINGIN_FAILED = 'FETCH_SINGIN_FAILED';

export const FETCH_REGISTER = 'FETCH_REGISTER';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILED = 'FETCH_REGISTER_FAILED';

export const FETCH_LISTUSER = 'FETCH_LISTUSER';
export const FETCH_LISTUSER_SUCCESS = 'FETCH_LISTUSER_SUCCESS';
export const FETCH_LISTUSER_FAILED = 'FETCH_LISTUSER_FAILED';